name: Release Linux App

on:
  workflow_dispatch
  # push:
  #   branches: [releases]
  # pull_request:
  #   branches:
  #     - master
  #   types: [closed]

env:
  NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
  GH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
  NOTARIZE_TOOL: notarytool
  APPLEID: ${{ secrets.APPLE_ID }}
  APPLEIDPASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
  APPLETEAMID: ${{ secrets.APPLE_TEAM_ID }}
  GOOGLE_OAUTH_CLIENT_ID: ${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}
  GOOGLE_OAUTH_CLIENT_SECRET: ${{ secrets.GOOGLE_OAUTH_CLIENT_SECRET }}

jobs:
  release-linux-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install project dependencies
        run: yarn install

      - name: 👷‍♂️ Building Linux application
        run: NODE_ENV=production yarn bozon package linux --publish
