name: Release Mac App

on:
  workflow_dispatch

  # push:
  #   branches: [releases]
  # pull_request:
  #   branches:
  #     - master
  #   types: [closed]

env:
  NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
  GH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
  NOTARIZE_TOOL: notarytool
  APPLEID: ${{ secrets.APPLE_ID }}
  APPLEIDPASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
  APPLETEAMID: ${{ secrets.APPLE_TEAM_ID }}
  GOOGLE_OAUTH_CLIENT_ID: ${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}
  GOOGLE_OAUTH_CLIENT_SECRET: ${{ secrets.GOOGLE_OAUTH_CLIENT_SECRET }}

jobs:
  release-macos-application:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
          p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}

      # - name: Setup upterm session
      #   uses: lhotari/action-upterm@v1
      #   with:
      #     ## limits ssh access and adds the ssh public key for the user which triggered the workflow
      #     limit-access-to-actor: true
      #     ## limits ssh access and adds the ssh public keys of the listed GitHub users
      #     limit-access-to-users: alchaplinsky

      - name: Install project dependencies
        run: yarn install

      - name: 👷‍♂️ Building MacOS application
        run: NODE_ENV=production yarn bozon package mac --publish
